receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlphttp/qryn:
    endpoint: http://qryn:3100
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/qryn]
